/* The following code was generated by JFlex 1.6.1 */

import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/autofs/unitytravail/travail/xgerardin/L3/Compilation/td2/jflex/Tokenizer.jflex</tt>
 */
public class Tokenizer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int COMMENT_DOC = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\62\1\62\1\62\1\62\22\0\1\65\1\34\1\63\2\0"+
    "\1\42\1\36\1\0\1\50\1\51\1\40\1\33\1\45\1\35\1\54"+
    "\1\41\12\57\1\47\1\46\1\30\1\31\1\32\1\0\1\64\4\61"+
    "\1\60\25\61\1\52\1\0\1\53\1\43\1\61\1\0\1\6\1\1"+
    "\1\10\1\17\1\5\1\20\1\22\1\13\1\15\1\61\1\7\1\3"+
    "\1\21\1\14\1\2\1\23\1\61\1\4\1\11\1\12\1\16\1\25"+
    "\1\24\1\61\1\27\1\26\1\55\1\37\1\56\1\44\6\0\1\62"+
    "\u1fa2\0\1\62\1\62\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\22\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\1\1\0\2\1\26\2\1\33"+
    "\2\2\1\34\13\2\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\2\0\1\62\1\63\4\0\24\2\1\64\4\2\1\65"+
    "\2\2\1\66\6\2\1\67\12\2\1\70\1\71\1\72"+
    "\1\61\1\0\1\61\4\0\1\73\2\2\1\74\2\2"+
    "\1\75\1\76\3\2\1\77\1\2\1\100\6\2\1\101"+
    "\2\2\1\102\14\2\1\103\4\2\1\104\1\2\4\0"+
    "\1\105\4\2\1\106\1\2\1\107\1\110\2\2\1\111"+
    "\4\2\1\112\5\2\1\113\1\2\1\114\3\2\1\115"+
    "\1\2\1\116\3\2\1\117\1\2\4\0\1\2\1\120"+
    "\1\2\1\121\1\2\1\122\1\123\1\124\1\125\1\126"+
    "\2\2\1\127\2\2\1\130\1\2\1\131\1\132\1\2"+
    "\1\133\2\2\1\134\1\2\4\0\5\2\1\135\2\2"+
    "\1\136\1\2\1\137\1\140\2\0\1\141\1\0\1\142"+
    "\1\143\1\144\1\145\1\146\1\2\1\147\1\2\1\150"+
    "\1\151\1\152\1\153\1\154";

  private static int [] zzUnpackAction() {
    int [] result = new int[317];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a"+
    "\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da"+
    "\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\u0654\0\u068a"+
    "\0\u06c0\0\u06f6\0\242\0\242\0\242\0\242\0\242\0\242"+
    "\0\242\0\242\0\u072c\0\242\0\242\0\u0762\0\u0798\0\u07ce"+
    "\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e"+
    "\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e"+
    "\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde"+
    "\0\u01e6\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\u0e22\0\u0e58"+
    "\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66\0\u0f9c\0\u0fd2\0\u1008"+
    "\0\242\0\242\0\242\0\u103e\0\242\0\242\0\242\0\242"+
    "\0\242\0\242\0\242\0\242\0\242\0\242\0\242\0\u1074"+
    "\0\u10aa\0\242\0\242\0\u10e0\0\u1116\0\u0798\0\242\0\242"+
    "\0\u114c\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6"+
    "\0\u12fc\0\u1332\0\u1368\0\u139e\0\u13d4\0\u140a\0\u1440\0\u1476"+
    "\0\u14ac\0\u14e2\0\u1518\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626"+
    "\0\u01e6\0\u165c\0\u1692\0\u16c8\0\u16fe\0\u01e6\0\u1734\0\u176a"+
    "\0\u01e6\0\u17a0\0\u17d6\0\u180c\0\u1842\0\u1878\0\u18ae\0\u01e6"+
    "\0\u18e4\0\u191a\0\u1950\0\u1986\0\u19bc\0\u19f2\0\u1a28\0\u1a5e"+
    "\0\u1a94\0\u1aca\0\242\0\242\0\242\0\u1b00\0\u1b36\0\u1b36"+
    "\0\u1b6c\0\u1ba2\0\u1bd8\0\u1c0e\0\u01e6\0\u1c44\0\u1c7a\0\u01e6"+
    "\0\u1cb0\0\u1ce6\0\u1d1c\0\u01e6\0\u1d52\0\u1d88\0\u1dbe\0\u01e6"+
    "\0\u1df4\0\u01e6\0\u1e2a\0\u1e60\0\u1e96\0\u1ecc\0\u1f02\0\u1f38"+
    "\0\u01e6\0\u1f6e\0\u1fa4\0\u01e6\0\u1fda\0\u2010\0\u2046\0\u207c"+
    "\0\u20b2\0\u20e8\0\u211e\0\u2154\0\u218a\0\u21c0\0\u21f6\0\u222c"+
    "\0\u01e6\0\u2262\0\u2298\0\u22ce\0\u2304\0\u01e6\0\u233a\0\u2370"+
    "\0\u23a6\0\u23dc\0\u2412\0\u01e6\0\u2448\0\u247e\0\u24b4\0\u24ea"+
    "\0\u01e6\0\u2520\0\u01e6\0\u01e6\0\u2556\0\u258c\0\u01e6\0\u25c2"+
    "\0\u25f8\0\u262e\0\u2664\0\u01e6\0\u269a\0\u26d0\0\u2706\0\u273c"+
    "\0\u2772\0\u01e6\0\u27a8\0\u01e6\0\u27de\0\u2814\0\u284a\0\u01e6"+
    "\0\u2880\0\u01e6\0\u28b6\0\u28ec\0\u2922\0\u01e6\0\u2958\0\u298e"+
    "\0\u29c4\0\u29fa\0\u2a30\0\u2a66\0\u01e6\0\u2a9c\0\u01e6\0\u2ad2"+
    "\0\u01e6\0\u01e6\0\u01e6\0\u01e6\0\u01e6\0\u2b08\0\u2b3e\0\u01e6"+
    "\0\u2b74\0\u2baa\0\u01e6\0\u2be0\0\u01e6\0\u01e6\0\u2c16\0\u01e6"+
    "\0\u2c4c\0\u2c82\0\u01e6\0\u2cb8\0\u2cee\0\u2d24\0\u2d5a\0\u2d90"+
    "\0\u2dc6\0\u2dfc\0\u2e32\0\u2e68\0\u2e9e\0\u01e6\0\u2ed4\0\u2f0a"+
    "\0\u01e6\0\u2f40\0\u01e6\0\u01e6\0\u2f76\0\u2fac\0\u2d5a\0\u2fe2"+
    "\0\u01e6\0\u01e6\0\u01e6\0\u01e6\0\u01e6\0\u3018\0\u01e6\0\u304e"+
    "\0\u2f76\0\u2fac\0\u3084\0\u01e6\0\u01e6";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[317];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\2\12\1\13"+
    "\1\14\1\15\1\12\1\16\1\17\1\20\1\21\1\22"+
    "\1\12\1\23\1\24\1\25\1\26\2\12\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\2\12\1\4"+
    "\1\57\2\4\40\2\1\60\25\2\40\4\1\61\23\4"+
    "\1\62\1\4\67\0\1\12\1\63\1\12\1\64\23\12"+
    "\27\0\3\12\5\0\22\12\1\65\4\12\27\0\3\12"+
    "\5\0\1\12\1\66\25\12\27\0\3\12\5\0\4\12"+
    "\1\67\22\12\27\0\3\12\5\0\2\12\1\70\10\12"+
    "\1\71\13\12\27\0\3\12\5\0\27\12\27\0\3\12"+
    "\5\0\1\12\1\72\1\73\2\12\1\74\4\12\1\75"+
    "\14\12\27\0\3\12\5\0\11\12\1\76\1\77\1\12"+
    "\1\100\6\12\1\101\3\12\27\0\3\12\5\0\3\12"+
    "\1\102\1\103\5\12\1\104\13\12\1\105\27\0\3\12"+
    "\5\0\4\12\1\106\1\107\21\12\27\0\3\12\5\0"+
    "\13\12\1\110\3\12\1\111\7\12\27\0\3\12\5\0"+
    "\10\12\1\112\2\12\1\113\13\12\27\0\3\12\5\0"+
    "\1\12\1\114\2\12\1\115\22\12\27\0\3\12\5\0"+
    "\1\12\1\116\1\117\1\120\1\12\1\121\21\12\27\0"+
    "\3\12\5\0\1\12\1\122\25\12\27\0\3\12\5\0"+
    "\3\12\1\123\11\12\1\124\11\12\27\0\3\12\5\0"+
    "\12\12\1\125\14\12\27\0\3\12\5\0\1\12\1\126"+
    "\12\12\1\127\12\12\27\0\3\12\34\0\1\130\1\131"+
    "\65\0\1\132\65\0\1\133\1\134\64\0\1\135\1\0"+
    "\1\136\63\0\1\137\65\0\1\140\3\0\1\141\61\0"+
    "\1\142\4\0\1\143\60\0\1\144\5\0\1\145\57\0"+
    "\1\146\65\0\1\147\6\0\1\150\1\151\55\0\1\152"+
    "\65\0\1\153\113\0\1\154\13\0\1\155\46\0\1\154"+
    "\2\0\1\56\1\155\5\0\63\156\1\157\2\156\40\2"+
    "\1\60\1\160\24\2\41\0\1\160\30\0\1\161\1\0"+
    "\1\162\14\0\1\163\1\0\1\164\41\0\1\12\1\165"+
    "\25\12\27\0\3\12\5\0\4\12\1\166\22\12\27\0"+
    "\3\12\5\0\4\12\1\167\22\12\27\0\3\12\5\0"+
    "\13\12\1\170\13\12\27\0\3\12\5\0\11\12\1\171"+
    "\7\12\1\172\5\12\27\0\3\12\5\0\10\12\1\173"+
    "\16\12\27\0\3\12\5\0\15\12\1\174\11\12\27\0"+
    "\3\12\5\0\13\12\1\175\13\12\27\0\3\12\5\0"+
    "\5\12\1\176\21\12\27\0\3\12\5\0\10\12\1\177"+
    "\1\200\15\12\27\0\3\12\5\0\5\12\1\201\21\12"+
    "\27\0\3\12\5\0\3\12\1\202\1\12\1\203\21\12"+
    "\27\0\3\12\5\0\1\12\1\204\25\12\27\0\3\12"+
    "\5\0\21\12\1\205\3\12\1\206\1\12\27\0\3\12"+
    "\5\0\14\12\1\207\12\12\27\0\3\12\5\0\15\12"+
    "\1\210\10\12\1\211\27\0\3\12\5\0\20\12\1\212"+
    "\6\12\27\0\3\12\5\0\3\12\1\213\10\12\1\214"+
    "\12\12\27\0\3\12\5\0\22\12\1\215\4\12\27\0"+
    "\3\12\5\0\23\12\1\216\3\12\27\0\3\12\5\0"+
    "\20\12\1\217\6\12\27\0\3\12\5\0\2\12\1\220"+
    "\6\12\1\221\15\12\27\0\3\12\5\0\14\12\1\222"+
    "\12\12\27\0\3\12\5\0\10\12\1\223\3\12\1\224"+
    "\12\12\27\0\3\12\5\0\15\12\1\225\11\12\27\0"+
    "\3\12\5\0\2\12\1\226\14\12\1\227\7\12\27\0"+
    "\3\12\5\0\3\12\1\230\23\12\27\0\3\12\5\0"+
    "\1\12\1\231\25\12\27\0\3\12\5\0\14\12\1\232"+
    "\12\12\27\0\3\12\5\0\2\12\1\233\24\12\27\0"+
    "\3\12\5\0\11\12\1\234\15\12\27\0\3\12\5\0"+
    "\1\12\1\235\12\12\1\236\12\12\27\0\3\12\5\0"+
    "\1\237\26\12\27\0\3\12\5\0\14\12\1\240\12\12"+
    "\27\0\3\12\5\0\14\12\1\241\12\12\27\0\3\12"+
    "\5\0\3\12\1\242\23\12\27\0\3\12\35\0\1\243"+
    "\65\0\1\244\74\0\1\245\25\0\62\151\1\0\3\151"+
    "\5\0\1\246\51\0\1\154\1\246\40\0\1\247\1\0"+
    "\1\247\21\0\1\250\13\0\1\251\76\0\1\252\55\0"+
    "\1\253\64\0\1\254\61\0\2\12\1\255\24\12\27\0"+
    "\3\12\5\0\5\12\1\256\21\12\27\0\3\12\5\0"+
    "\3\12\1\257\23\12\27\0\3\12\5\0\21\12\1\260"+
    "\5\12\27\0\3\12\5\0\15\12\1\261\11\12\27\0"+
    "\3\12\5\0\14\12\1\262\12\12\27\0\3\12\5\0"+
    "\4\12\1\263\22\12\27\0\3\12\5\0\20\12\1\264"+
    "\6\12\27\0\3\12\5\0\10\12\1\265\1\266\15\12"+
    "\27\0\3\12\5\0\10\12\1\267\16\12\27\0\3\12"+
    "\5\0\4\12\1\270\22\12\27\0\3\12\5\0\7\12"+
    "\1\271\17\12\27\0\3\12\5\0\3\12\1\272\23\12"+
    "\27\0\3\12\5\0\15\12\1\273\11\12\27\0\3\12"+
    "\5\0\11\12\1\274\15\12\27\0\3\12\5\0\3\12"+
    "\1\275\23\12\27\0\3\12\5\0\13\12\1\276\13\12"+
    "\27\0\3\12\5\0\4\12\1\277\22\12\27\0\3\12"+
    "\5\0\11\12\1\300\15\12\27\0\3\12\5\0\4\12"+
    "\1\301\22\12\27\0\3\12\5\0\22\12\1\302\4\12"+
    "\27\0\3\12\5\0\1\12\1\303\25\12\27\0\3\12"+
    "\5\0\10\12\1\304\16\12\27\0\3\12\5\0\4\12"+
    "\1\305\22\12\27\0\3\12\5\0\4\12\1\306\22\12"+
    "\27\0\3\12\5\0\14\12\1\307\12\12\27\0\3\12"+
    "\5\0\13\12\1\310\13\12\27\0\3\12\5\0\14\12"+
    "\1\311\12\12\27\0\3\12\5\0\1\12\1\312\25\12"+
    "\27\0\3\12\5\0\1\313\26\12\27\0\3\12\5\0"+
    "\4\12\1\314\22\12\27\0\3\12\5\0\5\12\1\315"+
    "\21\12\27\0\3\12\5\0\5\12\1\316\21\12\27\0"+
    "\3\12\5\0\4\12\1\317\22\12\27\0\3\12\5\0"+
    "\10\12\1\320\16\12\27\0\3\12\5\0\1\12\1\321"+
    "\25\12\27\0\3\12\5\0\11\12\1\322\15\12\27\0"+
    "\3\12\5\0\24\12\1\323\2\12\27\0\3\12\5\0"+
    "\2\12\1\324\24\12\27\0\3\12\5\0\2\12\1\325"+
    "\24\12\27\0\3\12\5\0\16\12\1\326\10\12\27\0"+
    "\3\12\5\0\11\12\1\327\15\12\27\0\3\12\37\0"+
    "\1\250\1\0\1\250\21\0\1\250\65\0\1\250\20\0"+
    "\1\330\65\0\1\331\57\0\1\332\65\0\1\333\62\0"+
    "\6\12\1\334\20\12\27\0\3\12\5\0\5\12\1\335"+
    "\21\12\27\0\3\12\5\0\3\12\1\336\23\12\27\0"+
    "\3\12\5\0\10\12\1\337\16\12\27\0\3\12\5\0"+
    "\14\12\1\340\12\12\27\0\3\12\5\0\11\12\1\341"+
    "\15\12\27\0\3\12\5\0\14\12\1\342\12\12\27\0"+
    "\3\12\5\0\10\12\1\343\16\12\27\0\3\12\5\0"+
    "\12\12\1\344\14\12\27\0\3\12\5\0\7\12\1\345"+
    "\17\12\27\0\3\12\5\0\14\12\1\346\12\12\27\0"+
    "\3\12\5\0\11\12\1\347\15\12\27\0\3\12\5\0"+
    "\4\12\1\350\22\12\27\0\3\12\5\0\1\12\1\351"+
    "\25\12\27\0\3\12\5\0\7\12\1\352\17\12\27\0"+
    "\3\12\5\0\2\12\1\353\24\12\27\0\3\12\5\0"+
    "\23\12\1\354\3\12\27\0\3\12\5\0\13\12\1\355"+
    "\1\356\1\12\1\357\10\12\27\0\3\12\5\0\10\12"+
    "\1\360\16\12\27\0\3\12\5\0\13\12\1\361\13\12"+
    "\27\0\3\12\5\0\21\12\1\362\5\12\27\0\3\12"+
    "\5\0\21\12\1\363\5\12\27\0\3\12\5\0\13\12"+
    "\1\364\13\12\27\0\3\12\5\0\2\12\1\365\24\12"+
    "\27\0\3\12\5\0\11\12\1\366\15\12\27\0\3\12"+
    "\5\0\15\12\1\367\11\12\27\0\3\12\5\0\11\12"+
    "\1\370\15\12\27\0\3\12\5\0\13\12\1\371\13\12"+
    "\27\0\3\12\5\0\4\12\1\372\22\12\27\0\3\12"+
    "\5\0\4\12\1\373\22\12\27\0\3\12\5\0\5\12"+
    "\1\374\21\12\27\0\3\12\5\0\14\12\1\375\12\12"+
    "\27\0\3\12\5\0\4\12\1\376\22\12\27\0\3\12"+
    "\5\0\15\12\1\377\11\12\27\0\3\12\22\0\1\u0100"+
    "\62\0\1\u0101\60\0\1\u0102\70\0\1\u0103\55\0\11\12"+
    "\1\u0104\15\12\27\0\3\12\5\0\13\12\1\u0105\13\12"+
    "\27\0\3\12\5\0\11\12\1\u0106\15\12\27\0\3\12"+
    "\5\0\17\12\1\u0107\7\12\27\0\3\12\5\0\13\12"+
    "\1\u0108\13\12\27\0\3\12\5\0\11\12\1\u0109\15\12"+
    "\27\0\3\12\5\0\7\12\1\u010a\17\12\27\0\3\12"+
    "\5\0\16\12\1\u010b\10\12\27\0\3\12\5\0\17\12"+
    "\1\u010c\7\12\27\0\3\12\5\0\12\12\1\u010d\14\12"+
    "\27\0\3\12\5\0\5\12\1\u010e\21\12\27\0\3\12"+
    "\5\0\5\12\1\u010f\21\12\27\0\3\12\5\0\16\12"+
    "\1\u0110\10\12\27\0\3\12\5\0\4\12\1\u0111\22\12"+
    "\27\0\3\12\5\0\22\12\1\u0112\4\12\27\0\3\12"+
    "\5\0\4\12\1\u0113\22\12\27\0\3\12\5\0\13\12"+
    "\1\u0114\13\12\27\0\3\12\5\0\4\12\1\u0115\22\12"+
    "\27\0\3\12\5\0\4\12\1\u0116\22\12\27\0\3\12"+
    "\5\0\2\12\1\u0117\24\12\27\0\3\12\5\0\16\12"+
    "\1\u0118\10\12\27\0\3\12\5\0\7\12\1\u0119\17\12"+
    "\27\0\3\12\5\0\11\12\1\u011a\15\12\27\0\3\12"+
    "\5\0\7\12\1\u011b\17\12\27\0\3\12\5\0\5\12"+
    "\1\u011c\21\12\27\0\3\12\10\0\1\u011d\63\0\1\u011e"+
    "\104\0\1\u011f\61\0\1\u0120\51\0\1\12\1\u0121\25\12"+
    "\27\0\3\12\5\0\4\12\1\u0122\22\12\27\0\3\12"+
    "\5\0\15\12\1\u0123\11\12\27\0\3\12\5\0\11\12"+
    "\1\u0124\15\12\27\0\3\12\5\0\20\12\1\u0125\6\12"+
    "\27\0\3\12\5\0\17\12\1\u0126\7\12\27\0\3\12"+
    "\5\0\5\12\1\u0127\21\12\27\0\3\12\5\0\4\12"+
    "\1\u0128\22\12\27\0\3\12\5\0\11\12\1\u0129\15\12"+
    "\27\0\3\12\5\0\11\12\1\u012a\15\12\27\0\3\12"+
    "\5\0\4\12\1\u012b\22\12\27\0\3\12\5\0\2\12"+
    "\1\u012c\24\12\27\0\3\12\20\0\1\u012d\55\0\1\u012e"+
    "\61\0\62\u012f\1\0\3\u012f\2\0\1\u0130\64\0\3\12"+
    "\1\u0131\23\12\27\0\3\12\5\0\3\12\1\u0132\23\12"+
    "\27\0\3\12\5\0\4\12\1\u0133\22\12\27\0\3\12"+
    "\5\0\4\12\1\u0134\22\12\27\0\3\12\5\0\4\12"+
    "\1\u0135\22\12\27\0\3\12\5\0\7\12\1\u0136\17\12"+
    "\27\0\3\12\5\0\16\12\1\u0137\10\12\27\0\3\12"+
    "\5\0\4\12\1\u0138\22\12\27\0\3\12\4\0\62\u0139"+
    "\1\0\3\u0139\62\u013a\1\0\3\u013a\14\0\1\u013b\52\0"+
    "\4\12\1\u013c\22\12\27\0\3\12\5\0\16\12\1\u013d"+
    "\10\12\27\0\3\12\45\0\1\u013b\12\0\1\u013b\2\0"+
    "\1\u013b\5\0\1\u013b";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12474];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\36\1\10\11\1\1\2\11\2\1\1\0"+
    "\50\1\3\11\1\1\13\11\2\1\2\11\1\1\2\0"+
    "\2\11\4\0\56\1\3\11\1\1\1\0\1\1\4\0"+
    "\53\1\4\0\44\1\4\0\31\1\4\0\14\1\2\0"+
    "\1\1\1\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[317];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Tokenizer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 180) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 109: break;
          case 2: 
            { System.out.printf("IDENTIFICATOR:%s\n", yytext());
            }
          case 110: break;
          case 3: 
            { return new Token(Sym.MINOR , yytext(), yyline, yycolumn);
            }
          case 111: break;
          case 4: 
            { return new Token(Sym.ASSIGN , yytext(), yyline, yycolumn);
            }
          case 112: break;
          case 5: 
            { return new Token(Sym.MAJOR , yytext(), yyline, yycolumn);
            }
          case 113: break;
          case 6: 
            { return new Token(Sym.PLUS , yytext(), yyline, yycolumn);
            }
          case 114: break;
          case 7: 
            { return new Token(Sym.EXCLAMATION , yytext(), yyline, yycolumn);
            }
          case 115: break;
          case 8: 
            { return new Token(Sym.MINUS , yytext(), yyline, yycolumn);
            }
          case 116: break;
          case 9: 
            { return new Token(Sym.AND , yytext(), yyline, yycolumn);
            }
          case 117: break;
          case 10: 
            { return new Token(Sym.OR , yytext(), yyline, yycolumn);
            }
          case 118: break;
          case 11: 
            { return new Token(Sym.TIME , yytext(), yyline, yycolumn);
            }
          case 119: break;
          case 12: 
            { return new Token(Sym.SLASH , yytext(), yyline, yycolumn);
            }
          case 120: break;
          case 13: 
            { return new Token(Sym.PERCENT , yytext(), yyline, yycolumn);
            }
          case 121: break;
          case 14: 
            { return new Token(Sym.XOR , yytext(), yyline, yycolumn);
            }
          case 122: break;
          case 15: 
            { return new Token(Sym.TILDE , yytext(), yyline, yycolumn);
            }
          case 123: break;
          case 16: 
            { return new Token(Sym.COLON , yytext(), yyline, yycolumn);
            }
          case 124: break;
          case 17: 
            { return new Token(Sym.SEMICOLON , yytext(), yyline, yycolumn);
            }
          case 125: break;
          case 18: 
            { return new Token(Sym.DOUBE_DOT , yytext(), yyline, yycolumn);
            }
          case 126: break;
          case 19: 
            { return new Token(Sym.PARENTHESE_IN , yytext(), yyline, yycolumn);
            }
          case 127: break;
          case 20: 
            { return new Token(Sym.PARENTHESE_OUT , yytext(), yyline, yycolumn);
            }
          case 128: break;
          case 21: 
            { return new Token(Sym.CROCHET_IN , yytext(), yyline, yycolumn);
            }
          case 129: break;
          case 22: 
            { return new Token(Sym.CROCHET_OUT , yytext(), yyline, yycolumn);
            }
          case 130: break;
          case 23: 
            { return new Token(Sym.DOT , yytext(), yyline, yycolumn);
            }
          case 131: break;
          case 24: 
            { return new Token(Sym.BRACKET_IN , yytext(), yyline, yycolumn);
            }
          case 132: break;
          case 25: 
            { return new Token(Sym.BRACKET_OUT , yytext(), yyline, yycolumn);
            }
          case 133: break;
          case 26: 
            { System.out.printf("NUMBER:%s\n", yytext());
            }
          case 134: break;
          case 27: 
            { return new Token(Sym.IF       , yytext(), yyline, yycolumn);
            }
          case 135: break;
          case 28: 
            { return new Token(Sym.DO       , yytext(), yyline, yycolumn);
            }
          case 136: break;
          case 29: 
            { return new Token(Sym.LEFT_SHIFT , yytext(), yyline, yycolumn);
            }
          case 137: break;
          case 30: 
            { return new Token(Sym.MINOR_EQUAL , yytext(), yyline, yycolumn);
            }
          case 138: break;
          case 31: 
            { return new Token(Sym.EQUAL , yytext(), yyline, yycolumn);
            }
          case 139: break;
          case 32: 
            { return new Token(Sym.MAJOR_EQUAL , yytext(), yyline, yycolumn);
            }
          case 140: break;
          case 33: 
            { return new Token(Sym.RIGHT_SHIFT , yytext(), yyline, yycolumn);
            }
          case 141: break;
          case 34: 
            { return new Token(Sym.PLUS_EQUAL , yytext(), yyline, yycolumn);
            }
          case 142: break;
          case 35: 
            { return new Token(Sym.MORE_MORE , yytext(), yyline, yycolumn);
            }
          case 143: break;
          case 36: 
            { return new Token(Sym.DIFFERENT , yytext(), yyline, yycolumn);
            }
          case 144: break;
          case 37: 
            { return new Token(Sym.MINUS_EQUAL , yytext(), yyline, yycolumn);
            }
          case 145: break;
          case 38: 
            { return new Token(Sym.MINUS_MINUS , yytext(), yyline, yycolumn);
            }
          case 146: break;
          case 39: 
            { return new Token(Sym.AND_EQUAL , yytext(), yyline, yycolumn);
            }
          case 147: break;
          case 40: 
            { return new Token(Sym.LOGICAL_AND , yytext(), yyline, yycolumn);
            }
          case 148: break;
          case 41: 
            { return new Token(Sym.OR_EQUAL , yytext(), yyline, yycolumn);
            }
          case 149: break;
          case 42: 
            { return new Token(Sym.LOGICAL_OR , yytext(), yyline, yycolumn);
            }
          case 150: break;
          case 43: 
            { return new Token(Sym.TIME_EQUAL , yytext(), yyline, yycolumn);
            }
          case 151: break;
          case 44: 
            { return new Token(Sym.DIVIDE_EQUAL , yytext(), yyline, yycolumn);
            }
          case 152: break;
          case 45: 
            { System.out.println("COMMENTARY"); yybegin(COMMENT);
            }
          case 153: break;
          case 46: 
            { System.out.printf("LINE COMMENTARY:%s\n", yytext());
            }
          case 154: break;
          case 47: 
            { return new Token(Sym.MODULO_EQUAL , yytext(), yyline, yycolumn);
            }
          case 155: break;
          case 48: 
            { return new Token(Sym.XOR_EQUAL , yytext(), yyline, yycolumn);
            }
          case 156: break;
          case 49: 
            { System.out.printf("FLOAT:%s\n", yytext());
            }
          case 157: break;
          case 50: 
            { System.out.printf("STRING:%s\n", yytext());
            }
          case 158: break;
          case 51: 
            { yybegin(YYINITIAL);
            }
          case 159: break;
          case 52: 
            { return new Token(Sym.TRY      , yytext(), yyline, yycolumn);
            }
          case 160: break;
          case 53: 
            { return new Token(Sym.NEW      , yytext(), yyline, yycolumn);
            }
          case 161: break;
          case 54: 
            { return new Token(Sym.INT      , yytext(), yyline, yycolumn);
            }
          case 162: break;
          case 55: 
            { return new Token(Sym.FOR      , yytext(), yyline, yycolumn);
            }
          case 163: break;
          case 56: 
            { return new Token(Sym.RIGHT_SHIFT_EQUAL , yytext(), yyline, yycolumn);
            }
          case 164: break;
          case 57: 
            { return new Token(Sym.LEFT_SHIFT_EQUAL , yytext(), yyline, yycolumn);
            }
          case 165: break;
          case 58: 
            { System.out.println("COMMENTARY DOC"); yybegin(COMMENT_DOC);
            }
          case 166: break;
          case 59: 
            { return new Token(Sym.BOOL     , yytext(), yyline, yycolumn);
            }
          case 167: break;
          case 60: 
            { return new Token(Sym.LONG     , yytext(), yyline, yycolumn);
            }
          case 168: break;
          case 61: 
            { return new Token(Sym.ELSE	   , yytext(), yyline, yycolumn);
            }
          case 169: break;
          case 62: 
            { return new Token(Sym.ENUM     , yytext(), yyline, yycolumn);
            }
          case 170: break;
          case 63: 
            { return new Token(Sym.CASE     , yytext(), yyline, yycolumn);
            }
          case 171: break;
          case 64: 
            { return new Token(Sym.CHAR     , yytext(), yyline, yycolumn);
            }
          case 172: break;
          case 65: 
            { return new Token(Sym.TRUE     , yytext(), yyline, yycolumn);
            }
          case 173: break;
          case 66: 
            { return new Token(Sym.THIS     , yytext(), yyline, yycolumn);
            }
          case 174: break;
          case 67: 
            { return new Token(Sym.GOTO     , yytext(), yyline, yycolumn);
            }
          case 175: break;
          case 68: 
            { return new Token(Sym.VOID     , yytext(), yyline, yycolumn);
            }
          case 176: break;
          case 69: 
            { return new Token(Sym.BREAK    , yytext(), yyline, yycolumn);
            }
          case 177: break;
          case 70: 
            { return new Token(Sym.CONST    , yytext(), yyline, yycolumn);
            }
          case 178: break;
          case 71: 
            { return new Token(Sym.CLASS    , yytext(), yyline, yycolumn);
            }
          case 179: break;
          case 72: 
            { return new Token(Sym.CATCH    , yytext(), yyline, yycolumn);
            }
          case 180: break;
          case 73: 
            { return new Token(Sym.SHORT    , yytext(), yyline, yycolumn);
            }
          case 181: break;
          case 74: 
            { return new Token(Sym.THROW    , yytext(), yyline, yycolumn);
            }
          case 182: break;
          case 75: 
            { return new Token(Sym.USING    , yytext(), yyline, yycolumn);
            }
          case 183: break;
          case 76: 
            { return new Token(Sym.UNION    , yytext(), yyline, yycolumn);
            }
          case 184: break;
          case 77: 
            { return new Token(Sym.FLOAT    , yytext(), yyline, yycolumn);
            }
          case 185: break;
          case 78: 
            { return new Token(Sym.FALSE    , yytext(), yyline, yycolumn);
            }
          case 186: break;
          case 79: 
            { return new Token(Sym.WHILE    , yytext(), yyline, yycolumn);
            }
          case 187: break;
          case 80: 
            { return new Token(Sym.RETURN   , yytext(), yyline, yycolumn);
            }
          case 188: break;
          case 81: 
            { return new Token(Sym.ELSEIF   , yytext(), yyline, yycolumn);
            }
          case 189: break;
          case 82: 
            { return new Token(Sym.STRUCT   , yytext(), yyline, yycolumn);
            }
          case 190: break;
          case 83: 
            { return new Token(Sym.STATIC   , yytext(), yyline, yycolumn);
            }
          case 191: break;
          case 84: 
            { return new Token(Sym.SIGNED   , yytext(), yyline, yycolumn);
            }
          case 192: break;
          case 85: 
            { return new Token(Sym.SIZEOF   , yytext(), yyline, yycolumn);
            }
          case 193: break;
          case 86: 
            { return new Token(Sym.SWITCH   , yytext(), yyline, yycolumn);
            }
          case 194: break;
          case 87: 
            { return new Token(Sym.TYPEID   , yytext(), yyline, yycolumn);
            }
          case 195: break;
          case 88: 
            { return new Token(Sym.INLINE   , yytext(), yyline, yycolumn);
            }
          case 196: break;
          case 89: 
            { return new Token(Sym.DOUBLE   , yytext(), yyline, yycolumn);
            }
          case 197: break;
          case 90: 
            { return new Token(Sym.DELETE   , yytext(), yyline, yycolumn);
            }
          case 198: break;
          case 91: 
            { return new Token(Sym.FRIEND   , yytext(), yyline, yycolumn);
            }
          case 199: break;
          case 92: 
            { return new Token(Sym.PUBLIC   , yytext(), yyline, yycolumn);
            }
          case 200: break;
          case 93: 
            { return new Token(Sym.TYPEDEF  , yytext(), yyline, yycolumn);
            }
          case 201: break;
          case 94: 
            { return new Token(Sym.DEFAULT  , yytext(), yyline, yycolumn);
            }
          case 202: break;
          case 95: 
            { return new Token(Sym.PRIVATE  , yytext(), yyline, yycolumn);
            }
          case 203: break;
          case 96: 
            { return new Token(Sym.VIRTUAL  , yytext(), yyline, yycolumn);
            }
          case 204: break;
          case 97: 
            { System.out.printf("Param : %s\n", yytext());
            }
          case 205: break;
          case 98: 
            { return new Token(Sym.OPERATOR , yytext(), yyline, yycolumn);
            }
          case 206: break;
          case 99: 
            { return new Token(Sym.REGISTER , yytext(), yyline, yycolumn);
            }
          case 207: break;
          case 100: 
            { return new Token(Sym.CONTINUE , yytext(), yyline, yycolumn);
            }
          case 208: break;
          case 101: 
            { return new Token(Sym.TEMPLATE , yytext(), yyline, yycolumn);
            }
          case 209: break;
          case 102: 
            { return new Token(Sym.TYPENAME , yytext(), yyline, yycolumn);
            }
          case 210: break;
          case 103: 
            { return new Token(Sym.UNSIGNED , yytext(), yyline, yycolumn);
            }
          case 211: break;
          case 104: 
            { System.out.printf("return : %s\n", yytext());
            }
          case 212: break;
          case 105: 
            { System.out.printf("Author : %s\n", yytext());
            }
          case 213: break;
          case 106: 
            { System.out.printf("Version : %s\n", yytext());
            }
          case 214: break;
          case 107: 
            { return new Token(Sym.NAMESPACE, yytext(), yyline, yycolumn);
            }
          case 215: break;
          case 108: 
            { return new Token(Sym.PROTECTED, yytext(), yyline, yycolumn);
            }
          case 216: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
