import beaver.*;
import java.util.ArrayList;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "parserAb.grammar".
 */
public class ParserAb extends Parser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9nDZeiAW308HS#cRK4$tOUtxBeOJ57l0qNWmh4Or7Zm614SGADWIXShL2ak9sU$rUAFDtb" +
		"wgZFrvIsSteOxMynjq$sQ7ymRxGDtd1lS");

	static final Action RETURN2 = new Action() {
		public Symbol reduce(Symbol[] _symbols, int offset) {
			return _symbols[offset + 2];
		}
	};

	static final Action RETURN3 = new Action() {
		public Symbol reduce(Symbol[] _symbols, int offset) {
			return _symbols[offset + 3];
		}
	};

	private final Action[] actions;

	public ParserAb() {
		super(PARSING_TABLES);
		actions = new Action[] {
			RETURN2,	// [0] S = X NEWLINE; returns 'NEWLINE' although none is marked
			RETURN3,	// [1] X = A X B; returns 'B' although none is marked
			Action.NONE	// [2] X = 
		};
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
